### ISSUE TITLE
afQuickField Checkboxes are plain checkboxes

### ISSUE THREAD

**Issue by drew-y** [fabienb4/meteor-autoform-semantic-ui#10]
When using the #autoForm option with afQuickField, boolean values render as plain checkboxes. 

``` html
{{#autoForm collection="Posts" id="postForm" type="insert"}}
  {{> afQuickField name='boolField'}}
{{/autoForm}}
```

renders as

``` html
<input type="checkbox" value="true" name="boolField" id="BX57oMALTWTzXQdZj" data-schema-key="boolField">
```

**Comment by fabienb4** [comment]
You didn't set `semanticUI` as default template, result is, the `plain` template is used instead.

See: [Usage](https://github.com/fabienb4/meteor-autoform-semantic-ui#usage)

You can also set it in the `autoForm` declaration: 

``` js
{{#autoForm collection="Posts" id="postForm" type="insert" template="semanticUI"}}
  {{> afQuickField name='boolField'}}
{{/autoForm}}
```
