### ISSUE TITLE
JavaScript select input not working in Array Fields?

### ISSUE THREAD

**Issue by peXed** [fabienb4/meteor-autoform-semantic-ui#14]
Hello!

I'm currently trying to style on of my forms probably. Unfortunately, I can't get a field of an ArrayField to use the fancy javascript version of the semantic ui working.

In other fields it is working great, but it seems it is not working inside an ArrayField.

Do I do something wrong or is it a bug/limitation?

**Comment by fabienb4** [comment]
It is working for me.
Without your code, it's hard to say what's wrong. Send me the relevant pieces of code by email (on my profile), I'll try to figure out what's wrong.
