### ISSUE TITLE
Could you example for using the "search dropdown" like select2?

### ISSUE THREAD

**Issue by thearabbit** [fabienb4/meteor-autoform-semantic-ui#21]
Could you example for using the `search dropdown` like `select2`?

``` js
country: {
        type: String,
        optional: true,
        autoform: {
            type: "...............",
            options: function () {
                items = [
                    {value: "A", label: "A", icon: "bz flag"},
                    {value: "B", label: "B", icon: "bz flag"}
                    //... more
                ];

                return items;
            }
        }
    },
```

**Comment by abernix** [comment]
This is already in the docs.  Please read them -  you are very close.  (Just set `search` to `true` and `type` to `select`).  If you're not sure how to do this with SimpleSchema, please [read those docs too](https://github.com/aldeed/meteor-simple-schema).

`{{> afQuickField name="country" type="select" options=items search=true}}`

**Comment by fabienb4** [comment]
Thanks @abernix.

You can also do it like that:

``` js
  country: {
    type: String,
    optional: true,
    autoform: {
      type: "select",
      search: true,
      options: [
        { value: "A", label: "A", icon: "bz flag" },
        { value: "B", label: "B", icon: "bz flag" }
        //... more
      ]
    }
  }
```

**Comment by thearabbit** [comment]
Very thanks for your reply.
Could I use `image/html format` instead of icon `{value: ........., .............icon:...........}`?
Please example.

**Comment by abernix** [comment]
It only supports CSS classes.  If you want to use your own image, simply use your own custom CSS class.
