### ISSUE TITLE
Could I use date, dateTime, dateRange Picker with Sematic UI?

### ISSUE THREAD

**Issue by thearabbit** [fabienb4/meteor-autoform-semantic-ui#22]
I am a new for `Sematic UI`.
I want to use `date, dateTime, dateRange picker` in `Sematic UI`.
Have any plugin?, please help me.

**Comment by abernix** [comment]
Semantic UI does not have a built-in date picker at this time.  When it does, I'm sure this package will be updated to support it.  If you visit the feature request on the Semantic UI repo (Semantic-Org/Semantic-UI#191), you will find some other suggestions.

**Comment by fabienb4** [comment]
Thanks @abernix.

**Comment by acidjunk** [comment]
https://github.com/BreadMaker/semantic-ui-daterangepicker
