### ISSUE TITLE
useLabels=false not working

### ISSUE THREAD

**Issue by ghost** [fabienb4/meteor-autoform-semantic-ui#28]
@METEOR1.2

```
<div class="ui segment">
      {{#autoForm id="commentForm" type="insert" collection=Collections.Comments template="semanticUI"}}
        <div class="ui attached segment">
        {{> afQuickField name="rating" placeholder="Rate this chapter" useLabels=false}}
        {{> afQuickField name="text" useLabels=false search=true}}
        </div>
        <div class="ui two bottom attached buttons">
          <button type="submit" class="ui positive button">Submit</button>
          <button type="reset" class="ui negative button">Reset</button>
        </div>
      {{/autoForm}}
    </div>
```

![screen shot 2015-09-26 at 7 43 37 pm](https://cloud.githubusercontent.com/assets/12010368/10117582/5abac792-6486-11e5-8045-547aa2b5e0b2.jpg)

**Comment by abernix** [comment]
Ah, this is just a confusing aspect of the new README.  What you are looking for is `label=false` **not** `useLabels`.  `label=false` should give you what you need.

Further explanation: `label=false` is a standard `aldeed:autoform` feature, however, `useLabels` is a Semantic UI feature for _multiple selection_ on `ui dropdown` elements.  You can read more about how `useLabels` works by looking in the [Semantic UI Dropdown documentation](http://semantic-ui.com/modules/dropdown.html#text-labels).

**Comment by ghost** [comment]
You're right. Thanks for the nice explanation and package

**Comment by abernix** [comment]
Not my package!   But glad to help. :smile:
