### ISSUE TITLE
Select not updating formValues reactively

### ISSUE THREAD

**Issue by mbernath** [fabienb4/meteor-autoform-semantic-ui#36]
Hi,

after updating from 0.5.0 to 0.7.2 I experienced the following issue:

When the value of a select control (Semantic dropdown) has changed, the Autoform formValues would not be reactively updated.

I traced the error down to the select control not emitting `change` events on the hidden input control to which Autoform is listening.

I added an `onChange` hook to the dropdown as follows, which fixed the problem:

```
Template.afSelect_semanticUI.onRendered(function() {
    var inputControl = this.$('[data-schema-key]');
  this.$(this.firstNode).dropdown(_.extend({
        fullTextSearch:         this.data.atts.fullTextSearch || false,
        allowAdditions:         this.data.atts.allowAdditions || false,
        maxSelections:          this.data.atts.maxSelections || false,
    allowCategorySelection: this.data.atts.allowCategorySelection || false,
        useLabels:              this.data.atts.useLabels === false ? false : true,
        onChange: function (event) { inputControl.trigger('change',{ target: inputControl }); }
    }, this.data.atts.settings));
});
```

Have I missed out something or is that a bug? If yes, I would send a pull request...

**Comment by fabienb4** [comment]
This issue probably comes from the same problem as #33.

It seems semantic-ui is hijacking some of the inner workings of the select (update and such). I'm hoping they will update the code so that the work doesn't fall on package authors.

I will check it out too, just to be sure.

**Comment by steve-ross** [comment]
here is a simpler version which uses the semantic ui event:

```
Template.afSelect_semanticUI.onRendered(function() {
    var inputControl = this.$('[data-schema-key]');
    this.$(this.firstNode).dropdown(_.extend({
        fullTextSearch:         this.data.atts.fullTextSearch || false,
        allowAdditions:         this.data.atts.allowAdditions || false,
        maxSelections:          this.data.atts.maxSelections || false,
            allowCategorySelection: this.data.atts.allowCategorySelection || false,
        useLabels:              this.data.atts.useLabels === false ? false : true,
        onChange: function (event) { inputControl.dropdown('refresh'); }
    }, this.data.atts.settings));
});
```
