### ISSUE TITLE
Hard refresh or first page load select problem

### ISSUE THREAD

**Issue by fabienb4** [fabienb4/meteor-autoform-semantic-ui#39]
When first loading a page or doing a hard refresh on a page with a form associated with a document, the `select` inputs won't properly update to the values of the document.

I suspect the problem is linked to the fact that Semantic-UI hijacks some of the update/change events.

I don't have much time to investigate at the moment, any ideas appreciated!
#33 #37

**Comment by steve-ross** [comment]
Hmm... I'm not seeing this behavior with Semantic UI v2.1.6
