### ISSUE TITLE
setDefaultTemplate() doesn't work when schema is created on the front end

### ISSUE THREAD

**Issue by steve-ross** [fabienb4/meteor-autoform-semantic-ui#40]
This might not actually be an issue (or it might just be an issue with autoform) but, in our project (haven't tested it outside of the project yet). But it seems like the code below doesn't work when you create a schema that only exists on the front-end. 

```
Meteor.startup(() => {
  AutoForm.setDefaultTemplate("semanticUI");
});
```

**Comment by fabienb4** [comment]
Can you elaborate on the use case?
A code example would be nice, I can't see what you are trying to do.
I tried a client-only collection with a schema (client side only too), the template works.
