### ISSUE TITLE
How to listen for changes on dropdowns?

### ISSUE THREAD

**Issue by lfilho** [fabienb4/meteor-autoform-semantic-ui#41]
Hello, thanks for all your plugins :)

I might be missing something, but how do I listen to events on a Semantic UI dropdown?

I have a `{{> afQuickField name='myField' options=myOptions}}` but since it gets converted to a bunch of div's and hidden elements, how do I listen to the changes in the Dropdown?

Thank you!

**Comment by abernix** [comment]
Since these components use AutoForm, the [Callbacks and Hooks that AutoForm provides](https://github.com/aldeed/meteor-autoform#callbackshooks) might be what you're looking for?

Is there something that those hooks don't provide that you need?

**Comment by lfilho** [comment]
Hey @abernix thanks for replying. The thing is that those hooks are 1) for the whole form 2) for submission related events. What I want is just to listen for a dropdown change (without submitting the form yet).

The problem is that a Semanitc UI dropdown render a bunch of div's and hidden inputs to mimic a `<select>` behaviour... So I cannot listen to events as one normally would in a DOM element because of that...

**Comment by fabienb4** [comment]
This should do what you want:

Template:

``` js
{{> afQuickField name='myField' options=myOptions settings=settings}}
```

JS helper:

``` js
Template.whatever.helpers({
  myOptions() {
    // your options
  },
  settings() {
    return {
      onChange(value, text, $choice) {
        // handle event
      }
    };
  }
});
```

See [dropdown settings](http://semantic-ui.com/modules/dropdown.html#/settings) for all the events you can register this way.
Please remember to close the issue if this fixes your problem.

**Comment by lfilho** [comment]
Yes, the `onChange` was what I was looking for but couldn't find! Sorry for that!

**Comment by fabienb4** [comment]
Glad that worked for you! Don't hesitate to send me an email if you have any other problems (it's on my profile here).

**Comment by lfilho** [comment]
Thanks, Fabien! And thanks again for this nice package :)

Em dom, 6 de dez de 2015 às 19:18, Fabien Blanchard <
notifications@github.com> escreveu:
