### ISSUE TITLE
Flag icons not working

### ISSUE THREAD

**Issue by lfilho** [fabienb4/meteor-autoform-semantic-ui#47]
Hey @fabienb4 looks like the flag icons are not working.

My example:

```
                { label: __('english-usa'), value: 'en', icon: 'us flag' },
                { label: __('portuguese-brazil'), value: 'pt', icon: 'br flag' },
```

And it renders:

![image](https://cloud.githubusercontent.com/assets/282756/12621010/caae85f4-c505-11e5-88e0-c9d19feb5d82.png)

Seems like it's always rendering the first flag (Andorra / ad) in the sprite or something like that.

For reference: http://semantic-ui.com/elements/flag.html

**Comment by fabienb4** [comment]
Did you try in a clean project with no CSS customization? Seems to me like something is messing with Semantic-UI CSS. I just tried in a test project, it works fine for me.

**Comment by lfilho** [comment]
I don't have any CSS customization, except for a mere:

``` css
@media only screen and (max-width: 720px) {
    body {
        min-width: 300px !important;
        width: 100% !important;
    }
}
```

I did a `rm -rf .meteor/local` and tried again but the same thing happened.

Generated html looks fine:

![image](https://cloud.githubusercontent.com/assets/282756/12699009/bd8f0ebc-c793-11e5-938e-03de7f82405e.png)

and here is the CSS:

![image](https://cloud.githubusercontent.com/assets/282756/12699012/d4ba0916-c793-11e5-92a9-f59e186ffd47.png)

Note that the position is at `0px 0px` but never overriden. Shouldn't it be overriden somewhere later?

**Comment by lfilho** [comment]
Aw. Got it. Again, for some reason, I had to force a semantic ui rebuild. Deleted `.custom.semantic.json` and then it worked again. :unamused: 

Thanks for your help!

**Comment by fabienb4** [comment]
Semantic-UI's way of updating the code base... Always messing things up it looks like!
