### ISSUE TITLE
prompt error labels 

### ISSUE THREAD

**Issue by pociej** [fabienb4/meteor-autoform-semantic-ui#5]
is it possible to display validation error message in prompt label ?

**Comment by pociej** [comment]
@fabienb4 do you want to do it ? I want to PR and can include it..

**Comment by fabienb4** [comment]
A PR is always welcome. I'm currently looking for a nice way to do it, so please if you have an idea, I'll be happy to review it!

**Comment by fabienb4** [comment]
v0.3.4 should allow you to do want you asked!
