### ISSUE TITLE
custom attributes for select options 

### ISSUE THREAD

**Issue by pociej** [fabienb4/meteor-autoform-semantic-ui#6]
Now you cant set custom attribute, options array elements have only value and label ...

**Comment by abernix** [comment]
What sort of options are you trying to set and on what type of element?  On 'select' type, you can also  set the icon by simply passing "icon" with a class (i.e. 'cz flag').

**Comment by pociej** [comment]
i want to set custom html attr , 

```
items :function() {
  return : [
    {'value' : '1', label : 'label' , 'data-context' : 'context'
  ] 
}
```

in such case 'data-context' isnt set. Anyway i solved locally will make PR.
