### ISSUE TITLE
Quick Field with Array

### ISSUE THREAD

**Issue by JeremyBYU** [fabienb4/meteor-autoform-semantic-ui#8]
Doesn't seem to play well with arrays.  I have objects called Parameters that are in array in my schema.  The buttons to add or delete are scrunched up.

![image](https://cloud.githubusercontent.com/assets/6628085/7625918/40c88b26-f9c4-11e4-8e62-6b96db60210d.png)

Also I already had semantic installed before adding your package (official atmosphere package).  Before and after adding your package it looked about the same (i think the form expanded to window size, but I think that was it).

Thanks,

**Comment by fabienb4** [comment]
I think something is wrong somewhere else @JeremyBYU. It seems like part (or all) of semantic-ui is missing from your project.

For example semantic-ui makes form's labels `bold`, yours aren't. Plus arrays are working properly (except for the issue #7).

Here is an example of an array field: 

![array-field](https://cloud.githubusercontent.com/assets/8208974/7632339/5a6e1b32-fa09-11e4-93d7-4fb4a3017bff.png)

See? "Payments" is a block header attached to a segment for the array items. It looks like your output is missing CSS.

Did you remove `semantic:ui-css` package after adding `fabienb4:autoform-semantic-ui`? If so, you have to add it back. This package doesn't provide semantic-ui.

**Comment by fabienb4** [comment]
Added warning in README that semantic-ui isn't included in the package.

Feel free to re-open the issue if you still encounter the problem.

**Comment by JeremyBYU** [comment]
I apologize.  It seems that the call to set the default semantic template was not executed correctly. After executing correctly I am getting everything as expected.  Thank you so much.

**Comment by fabienb4** [comment]
Glad you found out what the problem was!

If you have more questions, don't hesitate to send me an email (in my profile)!
